version: '3'
services:
  db:
    image: mongo
    container_name: db
    ports:
      - "27017"
    volumes:
      - ~/.boardgames/data/db:/data/db
      - ~/.boardgames/data/configdb:/data/configdb

  web:
    env_file: .env
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: web
    ports:
      - "3000:3000"
    depends_on:
      - db